project:
  type: website
  output-dir: docs

website:
  title: "Meizhu Chen"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
  page-footer:
    left: "© 2026 Meizhu Chen"
    right: "Built with [Quarto](https://quarto.org/)"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



